import Link from 'next/link'; import { redirect } from 'next/navigation'; import { createClient } from '@/lib/supabase/server'; import { DashboardShell, type AppRole } from '../dashboard-shell'; import { saveAttendance } from './actions';

export default async function AttendancePage() {
  const supabase = await createClient(); const { data } = await supabase.auth.getClaims(); if (!data?.claims?.sub) redirect('/login');
  const { data: profile } = await supabase.from('profiles').select('full_name, role, is_active').eq('id', data.claims.sub).maybeSingle(); if (!profile || !['admin','teacher'].includes(profile.role) || !profile.is_active) redirect('/dashboard');
  const { data: events } = await supabase.from('attendance_events').select('id, service_date, title, opens_at, closes_at').order('service_date', { ascending: false }).limit(1); const event = events?.[0];
  const [{ data: students }, { data: records }] = await Promise.all([supabase.from('students').select('id, full_name, grade, class_name').eq('is_active', true).order('grade').order('full_name'), event ? supabase.from('attendance_records').select('student_id, status, checked_at').eq('event_id', event.id) : Promise.resolve({ data: [] })]);
  const recordMap = new Map((records ?? []).map(r => [r.student_id, r])); const presentCount = (records ?? []).filter(r => ['present','late'].includes(r.status)).length;
  return <DashboardShell profile={{ full_name: profile.full_name, role: profile.role as AppRole }} activeHref="/dashboard/attendance"><div className="module-heading"><div><p className="eyebrow">ATTENDANCE</p><h1>주일 출석관리</h1><span>{event ? `${event.service_date} ${event.title}` : '생성된 출석 회차가 없습니다.'}</span></div>{profile.role === 'admin' && <Link className="module-primary-link" href="/dashboard/attendance/qr">출석 QR 화면</Link>}</div>
    <section className="attendance-live-summary"><div><span>출석</span><strong>{presentCount}명</strong></div><div><span>미등록</span><strong>{Math.max((students?.length ?? 0) - (records?.length ?? 0), 0)}명</strong></div><div><span>전체</span><strong>{students?.length ?? 0}명</strong></div></section>
    <section className="attendance-roster">{event && (students ?? []).map(student => { const record = recordMap.get(student.id); return <article key={student.id}><div><b>{student.full_name}</b><span>{student.grade}학년 {student.class_name ?? '반 미정'}</span></div><form action={saveAttendance}><input type="hidden" name="event_id" value={event.id}/><input type="hidden" name="student_id" value={student.id}/><select name="status" defaultValue={record?.status ?? 'present'}><option value="present">출석</option><option value="late">지각</option><option value="excused">사유결석</option><option value="absent">결석</option></select><button>{record ? '수정' : '등록'}</button></form></article>; })}</section>
  </DashboardShell>;
}
