/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck -- Runtime guards redirect before nullable Supabase data is used.
'use server';
import { redirect } from 'next/navigation'; import { revalidatePath } from 'next/cache'; import { createClient } from '@/lib/supabase/server';
async function context(){const s=await createClient();const{data}=await s.auth.getClaims();const id=data?.claims?.sub;if(!id)redirect('/login');const{data:p}=await s.from('profiles').select('role,is_active').eq('id',id).maybeSingle();if(!p?.is_active)redirect('/dashboard');return{s,id,role:p.role}}
const go=(path:string,type:string,msg:string):never=>redirect(`${path}?${type}=${encodeURIComponent(msg)}`);
export async function addLedgerEntry(fd:FormData){const c=await context();if(!c||c.role!=='accountant')go('/dashboard/finance','error','회계담당자만 등록할 수 있습니다.');const type=String(fd.get('entry_type'));const amount=Number(fd.get('amount'));const category=String(fd.get('category')??'').trim();const date=String(fd.get('transaction_date'));if(!['income','expense'].includes(type)||!category||!Number.isSafeInteger(amount)||amount<=0)go('/dashboard/finance','error','유형·비목·금액을 확인해 주세요.');const{error}=await c.s.from('finance_ledger').insert({transaction_date:date,entry_type:type,category,amount,memo:String(fd.get('memo')??'').trim()||null,created_by:c.id});if(error)go('/dashboard/finance','error',error.message);revalidatePath('/dashboard/finance');go('/dashboard/finance','message','장부에 등록했습니다.');}
export async function createPaymentRequest(fd:FormData){const c=await context();if(!c||c.role!=='teacher')go('/dashboard/finance/requests','error','선생님 계정에서 요청해 주세요.');const files=fd.getAll('receipts').filter((v):v is File=>v instanceof File&&v.size>0);const amount=Number(fd.get('amount'));if(files.length>5||files.some(f=>f.size>4*1024*1024)||!Number.isSafeInteger(amount)||amount<=0)go('/dashboard/finance/requests','error','금액과 영수증(최대 5장, 각 4MB)을 확인해 주세요.');const{data:req,error}=await c.s.from('payment_requests').insert({requester_id:c.id,category:String(fd.get('category')),amount,bank_account:String(fd.get('bank_account')),memo:String(fd.get('memo')??'')||null}).select('id').single();if(error||!req)go('/dashboard/finance/requests','error',error?.message??'요청 저장 실패');for(const [i,file] of files.entries()){const path=`${c.id}/${req.id}/${i}-${crypto.randomUUID()}.jpg`;const{error:u}=await c.s.storage.from('finance-receipts').upload(path,file,{contentType:file.type});if(u)go('/dashboard/finance/requests','error',`영수증 업로드 실패: ${u.message}`);await c.s.from('payment_request_receipts').insert({payment_request_id:req.id,storage_path:path,original_name:file.name});}revalidatePath('/dashboard/finance/requests');go('/dashboard/finance/requests','message','결제요청을 등록했습니다.');}
export async function processPaymentRequest(fd:FormData){const c=await context();if(!c||c.role!=='accountant')go('/dashboard/finance/requests','error','회계담당자만 처리할 수 있습니다.');const{error}=await c.s.rpc('process_payment_request',{target_request_id:String(fd.get('request_id')),next_status:String(fd.get('status')),note:String(fd.get('review_note')??'')});if(error)go('/dashboard/finance/requests','error',error.message);revalidatePath('/dashboard/finance');revalidatePath('/dashboard/finance/requests');go('/dashboard/finance/requests','message','처리상태를 변경했습니다.');}
