import { redirect } from 'next/navigation'; import { createClient } from '@/lib/supabase/server'; import { DashboardShell, type AppRole } from '../dashboard-shell'; import { PointsManager } from './points-manager';

export default async function PointsPage() {
  const supabase = await createClient(); const { data } = await supabase.auth.getClaims(); if (!data?.claims?.sub) redirect('/login'); const { data: profile } = await supabase.from('profiles').select('full_name, role, is_active').eq('id', data.claims.sub).maybeSingle(); if (!profile || !['admin','teacher'].includes(profile.role) || !profile.is_active) redirect('/dashboard');
  const [{ data: balances }, { data: transactions }] = await Promise.all([supabase.from('student_point_balances').select('student_id, full_name, grade, class_name, balance').order('grade').order('full_name'), supabase.from('point_transactions').select('id, student_id, amount, awarded_by, created_at').order('created_at', { ascending: false }).limit(10)]);
  const awarderIds = [...new Set((transactions ?? []).map((item) => item.awarded_by).filter((id): id is string => Boolean(id)))];
  const { data: awarders } = awarderIds.length ? await supabase.from('profiles').select('id, full_name, role').in('id', awarderIds) : { data: [] };
  const nameMap = new Map((balances ?? []).map(s => [s.student_id, s.full_name])); const awarderMap = new Map((awarders ?? []).map(a => [a.id, a])); const total = (balances ?? []).reduce((sum, student) => sum + Number(student.balance), 0);
  return <DashboardShell profile={{ full_name: profile.full_name, role: profile.role as AppRole }} activeHref="/dashboard/points"><div className="module-heading"><div><p className="eyebrow">DREAM GEM</p><h1>드림보석 관리</h1><span>학생에게 보석을 지급하거나 차감하고 전체 잔액을 확인합니다.</span></div><strong className="gem-heading-total">전체 {total}개</strong></div>
    <PointsManager initialBalances={(balances ?? []).map((student) => ({ ...student, balance: Number(student.balance) }))} />
    <section className="point-history"><div className="point-history-title"><h2>최근 보석 내역</h2><span>최신 10건</span></div><div className="point-history-head"><span>날짜</span><span>학생</span><span>처리자</span><span>변경</span></div>{(transactions ?? []).map(t => { const awarder = t.awarded_by ? awarderMap.get(t.awarded_by) : null; return <div className="point-history-row" key={t.id}><time>{new Date(t.created_at).toLocaleString('ko-KR', { timeZone: 'Asia/Seoul', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</time><b>{nameMap.get(t.student_id) ?? '학생'}</b><span>{awarder?.full_name ?? '처리자'} <small>{awarder?.role === 'admin' ? '관리자' : '선생님'}</small></span><strong className={t.amount > 0 ? 'plus' : 'minus'}>{t.amount > 0 ? '+' : ''}{t.amount}</strong></div>; })}{(transactions ?? []).length === 0 && <p className="point-history-empty">최근 보석 내역이 없습니다.</p>}</section>
  </DashboardShell>;
}
