'use client';

import Image from 'next/image';
import { useMemo, useState } from 'react';
import { setAccountPassword, updateAccountProfile, updateAccountRole, updateTeacherBirthDate, updateTeacherPhoto, withdrawAccount } from './actions';

type Role = 'admin' | 'teacher' | 'parent' | 'student';
export type ManagedAccount = { id: string; email: string | null; full_name: string; phone: string | null; address: string | null; note: string | null; birth_date: string | null; role: string; roles: string[]; photoUrl: string | null };
const roleLabel: Record<string,string> = { admin: '관리자', teacher: '선생님', parent: '부모님', student: '학생' };
const roleOrder: Role[] = ['parent','student','teacher','admin'];

export function ActiveAccountManager({ accounts, currentUserId }: { accounts: ManagedAccount[]; currentUserId: string }) {
  const [query,setQuery] = useState(''); const [role,setRole] = useState('all'); const [selected,setSelected] = useState<ManagedAccount|null>(null);
  const visible = useMemo(() => accounts.filter((account) => (role === 'all' || account.roles.includes(role)) && (!query.trim() || `${account.full_name} ${account.email ?? ''} ${account.phone ?? ''}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))), [accounts,query,role]);
  const isSelf = selected?.id === currentUserId;
  return <>
    <div className="account-directory-toolbar"><label><span className="sr-only">계정 검색</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="이름·이메일·연락처 검색" /></label><select value={role} onChange={(event) => setRole(event.target.value)} aria-label="역할 필터"><option value="all">전체 역할</option>{roleOrder.map((item) => <option key={item} value={item}>{roleLabel[item]}</option>)}</select><b>{visible.length}개</b></div>
    <div className="account-directory"><div className="account-directory-head"><span>계정</span><span>역할</span><span>연락처</span><span>상태</span></div>{visible.map((account) => <button type="button" key={account.id} className="account-directory-row" onClick={() => setSelected(account)}>{account.photoUrl ? <Image src={account.photoUrl} alt="" width={38} height={38}/>:<i>{account.full_name.slice(0,1)}</i>}<span><strong>{account.full_name}</strong><small>{account.email ?? '이메일 없음'}</small></span><span className="directory-role-pills">{account.roles.map((item) => <em key={item}>{roleLabel[item] ?? item}</em>)}</span><span>{account.phone || '미입력'}</span><span className="active-status">활성</span></button>)}{visible.length === 0 && <p className="account-directory-empty">조건에 맞는 활성 계정이 없습니다.</p>}</div>
    {selected && <div className="student-modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target) setSelected(null); }}><section className="student-modal account-detail-modal" role="dialog" aria-modal="true" aria-labelledby="account-detail-title"><button type="button" className="student-modal-close" onClick={() => setSelected(null)} aria-label="닫기">×</button><div className="account-modal-title">{selected.photoUrl ? <Image src={selected.photoUrl} alt="" width={52} height={52}/>:<i>{selected.full_name.slice(0,1)}</i>}<div><p>활성 계정</p><h2 id="account-detail-title">{selected.full_name}</h2><span>{selected.email ?? '이메일 없음'}</span></div></div>
      <form action={updateAccountProfile} className="account-detail-form"><input type="hidden" name="user_id" value={selected.id}/><label><span>이름</span><input name="full_name" defaultValue={selected.full_name} required/></label><label><span>이메일 (로그인 아이디)</span><input value={selected.email ?? ''} readOnly/></label><label><span>연락처</span><input name="phone" defaultValue={selected.phone ?? ''} placeholder="미입력"/></label><label className="wide"><span>주소</span><input name="address" defaultValue={selected.address ?? ''} placeholder="미입력"/></label><label className="wide"><span>비고</span><textarea name="note" defaultValue={selected.note ?? ''} rows={2} placeholder="미입력"/></label><button type="submit">기본 정보 저장</button></form>
      <form action={updateAccountRole} className="account-modal-section"><input type="hidden" name="user_id" value={selected.id}/><h3>계정 권한</h3><div className="account-modal-roles">{roleOrder.map((item) => <label key={item}><input type="checkbox" name="roles" value={item} defaultChecked={selected.roles.includes(item)} disabled={isSelf}/>{roleLabel[item]}</label>)}</div><button type="submit" disabled={isSelf}>권한 저장</button>{isSelf && <small>현재 로그인한 관리자 자신의 권한은 변경할 수 없습니다.</small>}</form>
      {selected.roles.includes('teacher') && <div className="account-teacher-tools"><form action={updateTeacherPhoto}><input type="hidden" name="user_id" value={selected.id}/><label><span>선생님 얼굴 사진</span><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required/></label><button type="submit">사진 저장</button></form><form action={updateTeacherBirthDate}><input type="hidden" name="user_id" value={selected.id}/><label><span>생년월일</span><input type="date" name="birth_date" defaultValue={selected.birth_date ?? ''}/></label><button type="submit">생일 저장</button></form></div>}
      {!isSelf && <details className="account-modal-section"><summary>비밀번호 직접 변경</summary><form action={setAccountPassword} className="account-password-form"><input type="hidden" name="user_id" value={selected.id}/><input name="new_password" type="password" minLength={8} placeholder="새 비밀번호 8자 이상" required/><input name="new_password_confirm" type="password" minLength={8} placeholder="새 비밀번호 확인" required/><button type="submit">비밀번호 적용</button></form></details>}
      {!isSelf && <details className="account-modal-section danger"><summary>탈퇴 처리</summary><form action={withdrawAccount} className="account-withdraw-form"><input type="hidden" name="user_id" value={selected.id}/><input name="withdrawal_note" maxLength={200} placeholder="탈퇴 사유 (선택)"/><p>로그인만 차단하고 기존 데이터는 보존합니다.</p><button type="submit">탈퇴 계정으로 전환</button></form></details>}
    </section></div>}
  </>;
}
